name: Python Docker Host Runner

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Build Docker image
        run: sudo docker build -t palm_slack_bot_image .
        working-directory: .

      - name: Stop previous Docker container
        run: sudo docker stop palm_slack_bot_container || true
        continue-on-error: true

      - name: Remove previous Docker container
        run: sudo docker rm palm_slack_bot_container || true
        continue-on-error: true

      - name: Run Docker container
        run: sudo docker run -d --name palm_slack_bot_container palm_slack_bot_image
